import type { Profile, Project, Article, Skill, Experience, Education } from "../shared/schema";

export const mockProfile: Profile = {
  name: "Alex Morgan",
  title: "Full-Stack Developer",
  tagline: "I craft beautiful, performant web applications with modern technologies. Passionate about clean code, great UX, and solving complex problems.",
  bio: "I'm a full-stack developer with over 5 years of experience building web applications. I specialize in React, TypeScript, and Node.js, with a strong focus on creating intuitive user experiences. When I'm not coding, you can find me contributing to open-source projects, writing technical articles, or exploring new technologies. I believe in writing clean, maintainable code and am always eager to learn and grow.",
  email: "hello@alexmorgan.dev",
  location: "San Francisco, CA",
  avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
  resumeUrl: "#",
  social: {
    github: "https://github.com",
    linkedin: "https://linkedin.com",
    twitter: "https://twitter.com",
  },
};

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "E-Commerce Platform",
    description: "A modern e-commerce platform with real-time inventory management, secure payments, and an intuitive admin dashboard.",
    longDescription: "Built a full-featured e-commerce platform from the ground up, featuring real-time inventory tracking, Stripe payment integration, and a comprehensive admin dashboard. The platform handles thousands of daily transactions and serves customers across multiple regions.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
    category: "Web Application",
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe", "Redis"],
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: true,
  },
  {
    id: "2",
    title: "Task Management App",
    description: "A collaborative task management tool with real-time updates, team workspaces, and advanced filtering.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop",
    category: "Productivity",
    technologies: ["Next.js", "TypeScript", "Prisma", "WebSocket"],
    liveUrl: "https://example.com",
    githubUrl: "https://github.com",
    featured: false,
  },
  {
    id: "3",
    title: "Analytics Dashboard",
    description: "Real-time analytics dashboard with interactive charts, custom reports, and data visualization tools.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
    category: "Data Visualization",
    technologies: ["React", "D3.js", "GraphQL", "MongoDB"],
    githubUrl: "https://github.com",
    featured: false,
  },
  {
    id: "4",
    title: "Social Media App",
    description: "A modern social platform with real-time messaging, stories, and content sharing features.",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=600&fit=crop",
    category: "Social",
    technologies: ["React Native", "Firebase", "Node.js", "Socket.io"],
    liveUrl: "https://example.com",
    featured: false,
  },
  {
    id: "5",
    title: "AI Writing Assistant",
    description: "An AI-powered writing tool that helps users create, edit, and improve their content using machine learning.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=600&fit=crop",
    category: "AI/ML",
    technologies: ["Python", "OpenAI", "React", "FastAPI"],
    githubUrl: "https://github.com",
    featured: false,
  },
  {
    id: "6",
    title: "Fitness Tracker",
    description: "A comprehensive fitness tracking app with workout plans, progress tracking, and social features.",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop",
    category: "Health & Fitness",
    technologies: ["React Native", "Node.js", "MongoDB", "Chart.js"],
    liveUrl: "https://example.com",
    featured: false,
  },
];

export const mockArticles: Article[] = [
  {
    id: "1",
    title: "Building Scalable React Applications with TypeScript",
    excerpt: "Learn how to structure your React applications for scale using TypeScript, best practices for state management, and tips for maintaining clean code.",
    content: "# Building Scalable React Applications with TypeScript\n\nReact applications can quickly become complex as they grow. In this article, we'll explore strategies for building scalable React applications using TypeScript.\n\n## Project Structure\n\nA well-organized project structure is the foundation of a scalable application. Consider organizing your code by feature rather than by type.\n\n## State Management\n\nChoose the right state management solution for your needs. For simple apps, React's built-in state might be enough. For complex apps, consider Redux or Zustand.\n\n## TypeScript Best Practices\n\n- Use strict mode\n- Define interfaces for props and state\n- Leverage generics for reusable components\n\n## Conclusion\n\nBuilding scalable React applications requires thoughtful architecture and consistent patterns throughout your codebase.",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=600&fit=crop",
    readTime: 8,
    publishedAt: "2024-12-01",
    tags: ["React", "TypeScript", "Architecture"],
    featured: true,
  },
  {
    id: "2",
    title: "Modern CSS Techniques Every Developer Should Know",
    excerpt: "Explore the latest CSS features including container queries, cascade layers, and the :has() selector that are changing how we write styles.",
    content: "# Modern CSS Techniques Every Developer Should Know\n\nCSS has evolved significantly over the past few years. Let's explore some modern techniques.\n\n## Container Queries\n\nContainer queries allow you to style elements based on their container's size rather than the viewport.\n\n## Cascade Layers\n\nLayers give you more control over the cascade, making it easier to manage styles from different sources.\n\n## The :has() Selector\n\nOften called the 'parent selector', :has() opens up new possibilities for styling based on content.\n\n## Conclusion\n\nThese modern CSS features make writing maintainable styles easier than ever.",
    image: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&h=600&fit=crop",
    readTime: 6,
    publishedAt: "2024-11-15",
    tags: ["CSS", "Web Development", "Frontend"],
    featured: false,
  },
  {
    id: "3",
    title: "Getting Started with Server Components in Next.js",
    excerpt: "A comprehensive guide to understanding and implementing React Server Components in your Next.js applications.",
    content: "# Getting Started with Server Components in Next.js\n\nReact Server Components are a game-changer for building performant web applications.\n\n## What are Server Components?\n\nServer Components render on the server and send HTML to the client, reducing the JavaScript bundle size.\n\n## When to Use Server Components\n\nUse them for data fetching, accessing backend resources, and heavy computations.\n\n## Best Practices\n\n- Keep interactive elements in Client Components\n- Use Server Components for data fetching\n- Compose Server and Client Components effectively",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop",
    readTime: 10,
    publishedAt: "2024-11-01",
    tags: ["Next.js", "React", "Server Components"],
    featured: false,
  },
  {
    id: "4",
    title: "Mastering Git: Advanced Workflows for Teams",
    excerpt: "Level up your Git skills with advanced branching strategies, rebasing techniques, and collaboration workflows for development teams.",
    content: "# Mastering Git: Advanced Workflows for Teams\n\nGit is essential for modern development. Let's explore advanced workflows.\n\n## Branching Strategies\n\nLearn about Git Flow, GitHub Flow, and trunk-based development.\n\n## Rebasing vs Merging\n\nUnderstand when to use each approach for cleaner history.\n\n## Collaboration Tips\n\n- Write meaningful commit messages\n- Use pull request templates\n- Set up branch protection rules",
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&h=600&fit=crop",
    readTime: 7,
    publishedAt: "2024-10-20",
    tags: ["Git", "DevOps", "Collaboration"],
    featured: false,
  },
];

export const mockSkills: Skill[] = [
  { id: "1", name: "React", category: "frontend", icon: "react" },
  { id: "2", name: "TypeScript", category: "frontend", icon: "typescript" },
  { id: "3", name: "Next.js", category: "frontend", icon: "nextjs" },
  { id: "4", name: "Tailwind CSS", category: "frontend", icon: "tailwind" },
  { id: "5", name: "Node.js", category: "backend", icon: "nodejs" },
  { id: "6", name: "Python", category: "backend", icon: "python" },
  { id: "7", name: "PostgreSQL", category: "backend", icon: "postgresql" },
  { id: "8", name: "GraphQL", category: "backend", icon: "graphql" },
  { id: "9", name: "Git", category: "tools", icon: "git" },
  { id: "10", name: "Docker", category: "tools", icon: "docker" },
  { id: "11", name: "AWS", category: "tools", icon: "aws" },
  { id: "12", name: "CI/CD", category: "tools", icon: "default" },
  { id: "13", name: "Figma", category: "design", icon: "figma" },
  { id: "14", name: "UI/UX Design", category: "design", icon: "default" },
  { id: "15", name: "Responsive Design", category: "design", icon: "mobile" },
  { id: "16", name: "Design Systems", category: "design", icon: "default" },
];

export const mockExperience: Experience[] = [
  {
    id: "1",
    title: "Senior Full-Stack Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    startDate: "2022",
    description: "Leading development of scalable web applications, mentoring junior developers, and implementing best practices across the team.",
    current: true,
  },
  {
    id: "2",
    title: "Full-Stack Developer",
    company: "StartupXYZ",
    location: "New York, NY",
    startDate: "2020",
    endDate: "2022",
    description: "Built and maintained multiple client-facing applications, integrated third-party APIs, and improved application performance by 40%.",
    current: false,
  },
  {
    id: "3",
    title: "Junior Web Developer",
    company: "Digital Agency",
    location: "Boston, MA",
    startDate: "2019",
    endDate: "2020",
    description: "Developed responsive websites and web applications for various clients, collaborated with designers to implement pixel-perfect designs.",
    current: false,
  },
];

export const mockEducation: Education[] = [
  {
    id: "1",
    degree: "B.S. in Computer Science",
    institution: "University of California",
    location: "Berkeley, CA",
    startDate: "2015",
    endDate: "2019",
    description: "Focus on software engineering and web technologies. Dean's List all semesters.",
  },
];
